 apiVersion: v1
 kind: PersistentVolume
 metadata:
  name: moodle-mariadb-pv-volume
  labels:
    type: local
 spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
  name: moodle-mariadb-pv-claim
 spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
 apiVersion: v1
 kind: Service
 metadata:
  name: moodle-mariadb
  labels:
    app: moodle
 spec:
  ports:
    - port: 3306
  selector:
    app: moodle
    tier: mariadb
  clusterIP: None
---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
  name: moodle-mariadb
  labels:
    app: moodle
 spec:
  selector:
    matchLabels:
      app: moodle
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: mariadb
    spec:
      containers:
        - image: okalan/moodleoumoudb:latest3
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: " "
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: moodle-mariadb-pv-claim
