kind: Deployment
apiVersion: apps/v1
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: frontend
    spec:
      containers:
        - image: okalan/moodleoumou:latest3
          name: moodle
          env:
            - name: DB_PORT_3306_TCP_ADDR
              value: "3306"
            - name: DB_ENV_MYSQL_PASSWORD
              value: " "
            - name: DB_ENV_MYSQL_USER
              value: moodlehomie
            - name: DB_ENV_MYSQL_DATABASE
              value: moodle
            - name: DB_ENV_MYSQL_PASSWORD
              value: moodle
          ports:
            - containerPort: 80
              name: https
            - containerPort: 6443
              name: https
          volumeMounts:
            - name: moodle-persistent-storage
              mountPath: /var/www/moodledata
      volumes:
        - name: moodle-persistent-storage
          persistentVolumeClaim:
            claimName: moo-dle-pv-claim
