 kind: PersistentVolume
 apiVersion: v1
 metadata:
  name: moodle-pv-volume
  labels:
    type: local
 spec:
  storageClassName: do-block-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
  name: moodle-pv-claim
 spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
                                                                                                                            12,1          All
